### PR TITLE
two_arms_simulation adding code

### PR DESCRIPTION
**Pull request by jainajinkya**
Added functions for the left arm as well. Switch between one arm or two arms is based on the values of the vector configuration parameters: VECTOR_HAS_TWO_KINOVA_ARMS and VECTOR_HAS_TWO_ROBOTIQ_GRIPPERS, which can be changed in the vector_common/vector_config/vector_config.sh file. 
For launching wpi_jaco_wrapper for both the arms, a new file "teo_arms" is added in the wpi_jaco_wrapper repo

### CODE REVIEW

**Comment by vchu** [comment]
I tested the branches as specified by Ajinkya

**Comment by vchu** [comment]
I've tested the branch as specified by Ajinkya in these instructions:
1. You need to change the parameters VECTOR_HAS_TWO_KINOVA_ARMS and VECTOR_HAS_TWO_ROBOTIQ_GRIPPERS from false to true,  in the vector_common/vector_config/vector_config.sh file. 
2. Do catkin_make again from scratch. Resource the terminals.
3. For checking gazebo:
   run "roslaunch hlpr_gazebo vector.launch"
4. For checking moveit:
   run "roslaunch hlpr_wpi_jaco_moveit_config hlpr_wpi_jaco_simple_moveit.launch"  and run rviz in a new terminal
5. Check if you can switch the planning arm and plan the trajectory.

Overall, I am able to switch between arms in the rviz window and plan and execute a trajectory

A few comments and issues though:
1. From the other PR HLP-R/hlpr_simulator#2
   I believe the moveit_config needs to be tweaked due to this spamming message:

`[ WARN] [1472582481.256456826, 212.139000000]: The complete state of the robot is not yet known. Missing base_footprint/x, base_footprint/y, base_footprint/theta`
1. I did notice that the arm doesn't check for self-collisions. One of the arm paths collided with the other arm. Is this intended to be fixed in future commits? If so, with the spamming warns removed then it should be fine.

**Comment by jainajinkya** [comment]
Updated the code to address issue#1.
Issue#2 will be updated in the future commits.

**Comment by vchu** [comment]
Great, just tested it and confirmed that both issues are gone. Looks good to me to pull in. Travis is breaking because of other issues in the stanley vector repo. A separate PR has been filed to address it.

Ajinkya, you can go ahead and pull in the merge request.

**Pull request merged**
